### PR TITLE
Fix #27 by using Core.Compiler instead of Core.Inference on v0.7

### LINKED ISSUE #27: UndefVarError: Inference not defined
On Julia v0.7-alpha (I omitted deprecation warnings); it doesn't work even using the latest version of the package.

```julia
julia> using Memoize

julia> @memoize f(x) = x <= 1 ? 1 : x * f(x - 1)
f (generic function with 1 method)

julia> f(23)
8128291617894825984

julia> f(5)
ERROR: UndefVarError: Inference not defined
Stacktrace:
 [1] f(::Int64) at /home/giovanni/.julia/packages/Memoize/QPoI/src/Memoize.jl:109
 [2] top-level scope

```

### PR DESCRIPTION
**Pull request by Element-126**
Here is a quick workaround for issue #27.

There is probably a better solution, but at least this fixes the issue.

### CODE REVIEW

**Comment by Element-126** [comment]
BTW, the test suite still fails on 0.7. Not sure if this is related.
```julia
(v0.7) pkg> test Memoize
```
```julia
Test Failed at /home/user/.julia/dev/Memoize/test/runtests.jl:166
  Expression: kw_ellipsis() == []
   Evaluated: Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}() == Any[]
```

**Comment by Element-126** [comment]
The build seems to fail on v0.5/Linux for some external reason.

```
ERROR: GitError(Code:ERROR, Class:Net, SSL error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)
```

**Comment by Element-126** [comment]
Closing and reopening to trigger a new build.

**Comment by Element-126** [comment]
Still failing. This seems to be an [issue with the Travis testing environment](https://github.com/travis-ci/travis-ci/issues/9539).

**Comment by rdeits** [comment]
That SSL issue with github and Julia v0.5 is known, and v0.5 is unsupported anyway. I'd suggest just dropping Julia v0.5 entirely.

**Comment by Element-126** [comment]
Superseded by #29, which fixes all 0.7 deprecations.

**Pull request closed without merging**
